<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Storage Path
    |--------------------------------------------------------------------------
    |
    | The path where the index files will be stored.
    |
    */
    'storage_path' => storage_path('indexer'),

    /*
    |--------------------------------------------------------------------------
    | Token Types
    |--------------------------------------------------------------------------
    |
    | The types of tokens to generate for indexing.
    |
    */
    'token_types' => [
        'ngrams' => [
            'min_size' => 3,
            'max_size' => 5,
        ],
        'metaphone' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Limit
    |--------------------------------------------------------------------------
    |
    | The default limit for search results.
    |
    */
    'default_limit' => 100,

    /*
    |--------------------------------------------------------------------------
    | Enable Cache
    |--------------------------------------------------------------------------
    |
    | Whether to cache search results.
    |
    */
    'enable_cache' => true,

    /*
    |--------------------------------------------------------------------------
    | Cache TTL
    |--------------------------------------------------------------------------
    |
    | The time-to-live for cached search results in seconds.
    |
    */
    'cache_ttl' => 3600,

    /*
    |--------------------------------------------------------------------------
    | Batch Size
    |--------------------------------------------------------------------------
    |
    | Number of items to process per batch during indexing.
    |
    */
    'batch_size' => env('INDEXER_BATCH_SIZE', 50),

    /*
    |--------------------------------------------------------------------------
    | Model Indexables
    |--------------------------------------------------------------------------
    |
    | List of model classes to index.
    | The cluster will be dynamically generated by each model's getIndexableCluster() method.
    |
    */
    'model_indexables' => [
        // App\Models\User::class,
        // App\Models\Hospital::class,
        // App\Models\Specialty::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Text Length Limits
    |--------------------------------------------------------------------------
    |
    | full_text_max_length: Maximum length for full-text chunking.
    |   - Texts longer than this are split into chunks.
    |   - Default: 100 characters
    |
    | max_text_length: Maximum text length to index.
    |   - Prevents token explosion on very long texts.
    |   - Default: 1000 characters
    |
    */
    'full_text_max_length' => env('INDEXER_FULL_TEXT_MAX_LENGTH', 100),
    'max_text_length' => env('INDEXER_MAX_TEXT_LENGTH', 1000),
];
